"""Async Postgres client for the memory layer — one implementation of MemoryStore.

One MemoryDatabase per persona container (one connection pool per process).
On startup, init_schema() applies the idempotent schema. Recall is hybrid:
Postgres FTS (`tsvector`) + trigram + local semantic embeddings (pgvector
cosine). Embeddings are generated by a local model (see .embeddings), so
recall stays provider-independent.

This class satisfies `ports.MemoryStore` STRUCTURALLY — it does not inherit
from it, and nothing checks at import time. That is the point of a structural
port: an alternative store owes the same methods, not a base class. What it
does owe beyond the signatures is the scoring contract in `ports/memory.py`
(scores in [0, 1], comparable across queries), which the type system cannot
state and `evals/recall_cases.yaml` measures instead.

The extra methods here — init_schema, backfill_embeddings, fetch — are
deliberately NOT on the port. They are this backend's maintenance surface and
only the composition root calls them.
"""
from __future__ import annotations

import asyncio
import json
import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any
from urllib.parse import urlparse

import asyncpg

from ports import FactCandidate, MemoryCoreEntry, MemoryEntry, Neighbor, Scored

from .embeddings import Embedder
from .embeddings import to_pgvector as _to_pgvector
from .reranking import Reranker

if TYPE_CHECKING:
    from datetime import datetime
    from uuid import UUID

log = logging.getLogger(__name__)

# What backfill_embeddings re-embeds: everything missing an embedding, or --
# with force -- everything not embedded by the model named in $1.
_UNEMBEDDED = "SELECT id, title, content FROM memory_entries WHERE embedding IS NULL"
_UNEMBEDDED_FOR_MODEL = (
    "SELECT id, title, content FROM memory_entries "
    "WHERE embedding IS NULL OR embedding_model IS DISTINCT FROM $1"
)


def redact_dsn(dsn: str) -> str:
    """Strip the password out of a DSN.

    For error messages an operator may paste into a chat or an issue.
    """
    return re.sub(r"://([^:/@]+):[^@]*@", r"://\1:***@", dsn)


async def _embed_pg(
    embedder: Embedder, text: str, *, is_query: bool = False
) -> str | None:
    """Compute a pgvector literal for `text` off the event loop; None on failure.

    `is_query` picks the query-side encoder. Retrieval is asymmetric — a short
    question and the long fact that answers it are encoded differently — so
    the search path must pass is_query=True. Getting this wrong doesn't raise;
    it just quietly costs recall.
    """
    try:
        fn = embedder.embed_query if is_query else embedder.embed_passage
        vec = await asyncio.to_thread(fn, text)
        return _to_pgvector(vec)
    except Exception:
        log.debug("embedding failed; continuing without a vector", exc_info=True)
        return None

_SCHEMA_PATH = Path(__file__).parent / "schema.sql"

# ---- hybrid-recall fusion constants ----
#
# Reciprocal Rank Fusion. Each retrieval arm (FTS, trigram, vector) ranks the
# candidates independently; a row's score is the sum of 1/(K + rank) over the
# arms that found it.
#
# Why RRF and not "take the best of the three scores": ts_rank, trigram
# similarity, and cosine similarity are not on a common scale — ts_rank is
# typically 0.05-0.3 while cosine runs 0.3-0.9 — so a max() over them is
# really just "whatever the vector arm said", and any threshold tuned against
# it means something different depending on which arm won. RRF discards the
# magnitudes and keeps only the ordering, which is the part that's comparable.
RRF_K = 60                  # standard damping constant; larger = flatter
RRF_CANDIDATES = 50         # per-arm candidate depth before fusion

# Per-arm weights, tuned by sweeping `./manage eval-recall`.
#
# The vector arm leads because it is the only one that handles paraphrase,
# which is most of what a person actually asks. The keyword arms are kept at
# real (not token) weight because they rescue exactly the queries embeddings
# are worst at: bare identifiers and slugs ("BPI", "PHP") where there is no
# sentence to encode.
#
# History worth keeping: at equal weights this fusion scored 85% recall@4
# against 100% for the vector arm ALONE — the keyword arms were pure noise.
# The cause was the FTS config, not the arms: 'simple' does no stopword
# removal, so "what is my current job title" OR-matched every fact containing
# "is" or "my". Switching content_tsv to 'english' (see schema.sql) restored
# the arm, and these weights then score 100% / 0.975 — the same as vector
# alone, but with the identifier queries also covered.
#
# Re-tune after any embedding-model change; the balance is a property of the
# model, not of the corpus.
RRF_WEIGHT_VEC = 1.0
RRF_WEIGHT_FTS = 0.35
RRF_WEIGHT_TRG = 0.25

# Minimum cosine for a row to enter the VECTOR arm's candidate pool.
#
# THIS NUMBER IS A PROPERTY OF THE EMBEDDING MODEL, not a universal constant —
# re-derive it whenever EMBEDDING_MODEL changes. Models differ enormously in
# where "unrelated" sits: mxbai-embed-large-v1 scores completely unrelated
# text around 0.32-0.40, so the previous 0.25 admitted literally everything
# and the gate was inert. Measure the floor before setting it:
#
#     cos("zzz qqq xyzzy nonsense", "The user works at Acme")  = 0.40
#     cos("what is the capital of France", ...)                = 0.33
#     cos("where does the user work", ...)                     = 0.72
#
# Swept against evals/recall_cases.yaml, recall@4 stays at 100% across
# 0.25-0.55 while the false-inject rate goes 12.5% -> 0% at 0.40 and MRR
# improves to 0.975 at 0.50. Chosen mid-band rather than at the edge of the
# good region so it isn't balanced on a knife-edge.
#
# What it does NOT do is separate hard-but-real queries from gibberish — those
# are genuinely indistinguishable to both the embedder (0.4029 vs 0.4034) and
# the reranker (-10.47 vs -10.43). Precision on that boundary comes from
# having a real corpus and a relative floor, not from this gate.
VEC_MIN_SIMILARITY = 0.50

# Additive tie-breaker, ~60-day half-life. Small on purpose: recency should
# separate two near-equal facts, never outrank real evidence. Under max()
# fusion this was 0.08 against scores that clustered near 0.2 — a third of the
# signal. Against a normalized RRF score it needs to be much smaller.
RECENCY_BOOST_MAX = 0.03
RECENCY_HALFLIFE_DAYS = 60.0


def _entry(row: asyncpg.Record) -> MemoryEntry:
    """Map one `memory_entries` row onto the port's DTO.

    A module function rather than `MemoryEntry.from_row`: the DTO lives in
    `ports`, which may not import asyncpg (an enforced contract), so the row
    type can only be named on this side of the boundary. Every read path in
    this file goes through here — that is what keeps the driver's Record from
    escaping into the faculty.
    """
    return MemoryEntry(
        id=row["id"],
        persona_id=row["persona_id"],
        scope=row["scope"],
        domain_key=row["domain_key"],
        title=row["title"],
        content=row["content"],
        metadata=dict(row["metadata"] or {}),
        superseded_by=row["superseded_by"],
        created_at=row["created_at"],
        updated_at=row["updated_at"],
        pinned=bool(row["pinned"]) if "pinned" in row else False,
        volatile=bool(row["volatile"]) if "volatile" in row else False,
        verified_at=row.get("verified_at", None),
        # `in row` guards throughout: several read paths SELECT a projection
        # rather than *, and a KeyError here would take out recall entirely
        # over a column that has a sensible default.
        valid_from=row.get("valid_from", None),
        valid_to=row.get("valid_to", None),
        provenance=(row.get("provenance", None)) or "chat",
        confidence=(
            float(row["confidence"]) if "confidence" in row
            and row["confidence"] is not None else 1.0
        ),
    )



# The recall query, whole. Three ranked arms over one candidate base, fused with
# weighted RRF and nudged by recency.
#
# An arm switches off by having its parameter bound to NULL, which is why this
# can be one static statement rather than a string assembled per call: the
# planner sees the same text every time, and so does anyone reading it.
_RECALL_SQL = """
WITH base AS (
    SELECT * FROM memory_entries
    WHERE persona_id = $1 AND superseded_by IS NULL
      -- Bi-temporal gate. All three arms rank the same `base`, so putting
      -- expiry here covers every retrieval path at once rather than needing
      -- the predicate repeated (and eventually forgotten) in one of them.
      --
      -- valid_to is NULL for almost every fact — "no known end" — and the
      -- partial index makes the exception cheap. What this stops is the case
      -- write-time reasoning gets wrong: "the user is on leave 12-19 Aug" is
      -- the freshest un-superseded fact on 25 Aug, so without this it is
      -- still recalled, still injected, and still acted on.
      AND (valid_to IS NULL OR valid_to > NOW())
      AND (valid_from IS NULL OR valid_from <= NOW())
      AND ($4::text IS NULL OR scope = $4)
      AND ($5::text IS NULL OR domain_key = $5)
),
-- Every tuning parameter is cast explicitly: left to infer, Postgres reads
-- them from the bigint rank arithmetic around them and silently truncates
-- max_rrf (~0.0098) to zero.
--
-- ROW_NUMBER then filter: a bare LIMIT would truncate before the window
-- function has ordered anything.
fts AS (
    SELECT id, rnk FROM (
        SELECT id, ROW_NUMBER() OVER (
            ORDER BY ts_rank(content_tsv, to_tsquery('english', $3)) DESC, id
        ) AS rnk
        FROM base
        WHERE $3::text IS NOT NULL AND content_tsv @@ to_tsquery('english', $3)
    ) x WHERE rnk <= $9::bigint
),
trg AS (
    SELECT id, rnk FROM (
        SELECT id, ROW_NUMBER() OVER (ORDER BY similarity(content, $2) DESC, id) AS rnk
        FROM base WHERE content % $2
    ) x WHERE rnk <= $9::bigint
),
vec AS (
    SELECT id, rnk FROM (
        SELECT id, ROW_NUMBER() OVER (
            ORDER BY (1 - (embedding <=> $6::vector)) DESC, id
        ) AS rnk
        FROM base
        WHERE $6::vector IS NOT NULL
          AND embedding IS NOT NULL
          AND embedding_model = $7
          AND (1 - (embedding <=> $6::vector)) > $8::float8
    ) x WHERE rnk <= $9::bigint
),
ids AS (
    SELECT id FROM fts UNION SELECT id FROM trg UNION SELECT id FROM vec
)
SELECT m.*, LEAST(
    1.0,
    (COALESCE($11::float8 / ($10::float8 + fts.rnk), 0)
     + COALESCE($12::float8 / ($10::float8 + trg.rnk), 0)
     + COALESCE($13::float8 / ($10::float8 + vec.rnk), 0)) / $14::float8
    + $15::float8 * EXP(-EXTRACT(EPOCH FROM (NOW() - m.created_at)) / ($16::float8 * 86400.0))
) AS match_score
FROM ids
JOIN base m USING (id)
LEFT JOIN fts ON fts.id = ids.id
LEFT JOIN trg ON trg.id = ids.id
LEFT JOIN vec ON vec.id = ids.id
ORDER BY match_score DESC, m.created_at DESC
LIMIT $17::bigint
"""


class MemoryDatabase:
    """Async Postgres-backed memory store. One per persona container.

    `connect()` also applies the schema, matching ConversationHistory and
    CommsLog. Callers therefore only owe `connect()`, which is the whole of
    `MemoryStore`'s lifecycle contract — the faculty used to call
    `init_schema()` too, and "you must run this Postgres-shaped migration
    step" is not something a port can ask of a store that isn't Postgres.
    `init_schema` stays public and is idempotent, so calling it again costs
    nothing.

    `migrate=False` opts out of that, for a caller that must be certain it
    cannot move DDL on a database it does not own. This exists because
    connect()-applies-schema turned every read-only consumer into a
    migration: the recall eval — a benchmark, and documented as safe to
    point at a live database — silently migrated production the first time
    it ran after that change. It seeds and deletes its own throwaway
    persona, so no DATA was ever at risk; the schema was, and nothing in the
    call said so.

    Owning the schema and reading the data are different privileges. Only
    the composition root has the first.
    """

    def __init__(
        self,
        dsn: str,
        *,
        migrate: bool = True,
        embedder: Embedder | None = None,
        reranker: Reranker | None = None,
    ) -> None:
        self._dsn = dsn
        self._migrate = migrate
        # Injected, because which model wrote a vector is a property of THIS
        # database — it sizes the vector column and is stored per row. The
        # defaults are the documented ones, so a test or a script that
        # doesn't care can leave them out; the composition root always passes
        # what the operator configured.
        self._embed = embedder or Embedder()
        self._rerank = reranker or Reranker()
        self._pool: asyncpg.Pool | None = None

    @property
    def embedder(self) -> Embedder:
        """Which model this store writes vectors with.

        Read by the shared-database guard in the composition root.
        """
        return self._embed

    async def connect(self) -> None:
        if self._pool is not None:
            return
        # JSONB codec must be registered on every connection the pool hands
        # out; set_type_codec only sticks for the conn it's called on.
        async def _init_conn(conn: asyncpg.Connection) -> None:
            await conn.set_type_codec(
                "jsonb",
                encoder=_jsonb_encoder,
                decoder=_jsonb_decoder,
                schema="pg_catalog",
            )
        self._pool = await asyncpg.create_pool(
            self._dsn, min_size=1, max_size=4, init=_init_conn,
        )
        log.info("memory database connected (dsn host=%s)", _dsn_host(self._dsn))
        if self._migrate:
            await self.init_schema()

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    async def init_schema(self) -> None:
        """Apply the idempotent schema, templated with the current embedding width.

        `{{EMBED_DIM}}` is substituted rather than hardcoded so that changing EMBEDDING_MODEL
        migrates the column instead of failing every insert with a dimension mismatch.
        """
        sql = _SCHEMA_PATH.read_text(encoding="utf-8").replace(
            "{{EMBED_DIM}}", str(self._embed.dim)
        )
        async with self._acquire() as conn:
            await conn.execute(sql)

    # ---- entry CRUD ----

    async def save_entry(
        self,
        persona_id: str,
        fact: FactCandidate,
        *,
        metadata: dict[str, Any] | None = None,
    ) -> MemoryEntry:
        scope, content, title = fact.scope, fact.content, fact.title
        emb = await _embed_pg(self._embed, f"{title}\n{content}" if title else content)
        async with self._acquire() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO memory_entries
                    (persona_id, scope, domain_key, title, content, metadata,
                     embedding, embedding_model, volatile, verified_at,
                     provenance, confidence, valid_from, valid_to)
                VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::vector, $8, $9, NOW(),
                        $10, $11, COALESCE($12, NOW()), $13)
                RETURNING *
                """,
                persona_id, scope, fact.domain_key, title, content, metadata or {},
                emb, self._embed.model_name if emb else "", fact.volatile,
                fact.provenance, fact.confidence, fact.valid_from, fact.valid_to,
            )
        return _entry(row)

    async def expire_entry(self, entry_id: UUID, at: datetime) -> bool:
        """End a fact's validity without retracting it.

        Only ever moves the end date EARLIER (or sets it), via LEAST. An
        expiry that could be pushed out would let a stale re-extraction
        resurrect a fact the user already ended — the mistake runs one way
        here, so the SQL only permits the safe direction.
        """
        async with self._acquire() as conn:
            result = await conn.execute(
                """
                UPDATE memory_entries
                   SET valid_to = LEAST(COALESCE(valid_to, $2), $2),
                       updated_at = NOW()
                 WHERE id = $1 AND superseded_by IS NULL
                """,
                entry_id, at,
            )
        # asyncpg reports "UPDATE <n>" / "DELETE <n>"; 0 means nothing matched.
        return str(result).split()[-1] != "0"

    async def find_similar(
        self,
        persona_id: str,
        scope: str,
        domain_key: str,
        content: str,
        threshold: float = 0.90,
    ) -> tuple[MemoryEntry, float] | None:
        """Nearest active entry in the same compartment, by cosine similarity.

        Returned only if it clears `threshold`. Used to dedup near-identical
        saves (the model re-learning the same fact) before they accumulate.
        Returns (entry, similarity) or None. Trigram fallback when the
        embedding isn't available.
        """
        qpg = await _embed_pg(self._embed, content)
        async with self._acquire() as conn:
            if qpg:
                row = await conn.fetchrow(
                    """
                    SELECT *, (1 - (embedding <=> $4::vector)) AS sim
                    FROM memory_entries
                    WHERE persona_id = $1 AND scope = $2 AND domain_key = $3
                      AND superseded_by IS NULL
                      AND embedding IS NOT NULL AND embedding_model = $5
                    ORDER BY embedding <=> $4::vector
                    LIMIT 1
                    """,
                    persona_id, scope, domain_key, qpg, self._embed.model_name,
                )
            else:
                row = await conn.fetchrow(
                    """
                    SELECT *, similarity(content, $4) AS sim
                    FROM memory_entries
                    WHERE persona_id = $1 AND scope = $2 AND domain_key = $3
                      AND superseded_by IS NULL
                    ORDER BY similarity(content, $4) DESC
                    LIMIT 1
                    """,
                    persona_id, scope, domain_key, content,
                )
        if row is None or float(row["sim"] or 0) < threshold:
            return None
        return _entry(row), float(row["sim"])

    async def get_entry(self, entry_id: UUID) -> MemoryEntry | None:
        async with self._acquire() as conn:
            row = await conn.fetchrow(
                "SELECT * FROM memory_entries WHERE id = $1", entry_id
            )
        return _entry(row) if row else None

    async def supersede_entry(
        self,
        old_id: UUID,
        new_content: str,
    ) -> MemoryEntry | None:
        """Insert a new active entry that replaces `old_id`.

        Marks the old row's `superseded_by` to the new id. Returns the new entry, or None if the old
        id wasn't found / already superseded.
        """
        async with self._acquire() as conn, conn.transaction():
            old = await conn.fetchrow(
                """
                    SELECT * FROM memory_entries
                    WHERE id = $1 AND superseded_by IS NULL
                    """,
                old_id,
            )
            if old is None:
                return None
            emb = await _embed_pg(
                self._embed,
                f"{old['title']}\n{new_content}" if old["title"] else new_content)
            new = await conn.fetchrow(
                """
                    INSERT INTO memory_entries
                        (persona_id, scope, domain_key, title, content, metadata,
                         embedding, embedding_model, pinned, volatile, verified_at,
                         provenance, confidence, valid_from)
                    VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::vector, $8, $9, $10, NOW(),
                            $11, $12, NOW())
                    RETURNING *
                    """,
                old["persona_id"], old["scope"], old["domain_key"],
                old["title"], new_content, dict(old["metadata"] or {}),
                emb, self._embed.model_name if emb else "", old["pinned"], old["volatile"],
                # Provenance is inherited but validity is NOT: the
                # replacement starts being true now, whereas the old row
                # keeps the window it actually covered. Copying valid_from
                # forward would claim the corrected value had been true
                # all along, which is exactly the history this table is
                # supposed to preserve.
                old["provenance"], old["confidence"],
            )
            # Close the old row's validity window at the moment it was
            # replaced, so "what did I believe last Tuesday?" answers with
            # the value that was current then.
            await conn.execute(
                "UPDATE memory_entries SET valid_to = COALESCE(valid_to, NOW()) "
                "WHERE id = $1",
                old["id"],
            )
            await conn.execute(
                "UPDATE memory_entries SET superseded_by = $1, updated_at = NOW() WHERE id = $2",
                new["id"], old["id"],
            )
            # Carry the old entry's graph edges onto its replacement so a
            # correction doesn't orphan the fact's relationships. The new
            # row was just inserted and has no edges of its own, so no PK
            # collision is possible here.
            await conn.execute(
                "UPDATE memory_links SET from_id = $1 WHERE from_id = $2",
                new["id"], old["id"],
            )
            await conn.execute(
                "UPDATE memory_links SET to_id = $1 WHERE to_id = $2",
                new["id"], old["id"],
            )
        return _entry(new)

    # ---- links (typed edges between entries) ----

    async def add_link(
        self,
        from_id: UUID,
        to_id: UUID,
        relation: str = "relates_to",
    ) -> bool:
        """Create a directional edge from_id --relation--> to_id.

        Idempotent: returns True if a new edge was created, False if it already existed.
        """
        async with self._acquire() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO memory_links (from_id, to_id, relation)
                VALUES ($1, $2, $3)
                ON CONFLICT (from_id, to_id, relation) DO NOTHING
                RETURNING from_id
                """,
                from_id, to_id, relation,
            )
        return row is not None

    async def remove_link(
        self,
        from_id: UUID,
        to_id: UUID,
        relation: str | None = None,
    ) -> bool:
        """Delete the edge(s) between two entries.

        With `relation`, only that edge; without it, every edge from_id->to_id. Returns True if
        anything was deleted.
        """
        async with self._acquire() as conn:
            if relation is not None:
                result = await conn.execute(
                    "DELETE FROM memory_links WHERE from_id = $1 AND to_id = $2 AND relation = $3",
                    from_id, to_id, relation,
                )
            else:
                result = await conn.execute(
                    "DELETE FROM memory_links WHERE from_id = $1 AND to_id = $2",
                    from_id, to_id,
                )
        # asyncpg reports "UPDATE <n>" / "DELETE <n>"; 0 means nothing matched.
        return str(result).split()[-1] != "0"

    async def neighbors(
        self,
        entry_id: UUID,
    ) -> list[Neighbor]:
        """Directly-linked ACTIVE entries.

        Returns (neighbor, relation, direction) where direction is 'out' (entry_id --rel-->
        neighbor) or 'in' (neighbor --rel--> entry_id). Superseded/forgotten neighbors are excluded
        so recall never surfaces stale links.
        """
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT m.*, l.relation AS _rel, 'out' AS _dir
                FROM memory_links l JOIN memory_entries m ON m.id = l.to_id
                WHERE l.from_id = $1 AND m.superseded_by IS NULL
                UNION ALL
                SELECT m.*, l.relation AS _rel, 'in' AS _dir
                FROM memory_links l JOIN memory_entries m ON m.id = l.from_id
                WHERE l.to_id = $1 AND m.superseded_by IS NULL
                """,
                entry_id,
            )
        return [(_entry(r), r["_rel"], r["_dir"]) for r in rows]

    async def forget_entry(self, entry_id: UUID, hard: bool = False) -> bool:
        async with self._acquire() as conn:
            if hard:
                result = await conn.execute(
                    "DELETE FROM memory_entries WHERE id = $1", entry_id
                )
            else:
                # Soft-delete: mark in metadata and supersede with itself so
                # it drops out of "active" queries. We use a sentinel UUID
                # set to the entry itself to mark it tombstoned without
                # losing provenance.
                result = await conn.execute(
                    """
                    UPDATE memory_entries
                    SET superseded_by = id,
                        metadata = metadata || jsonb_build_object('forgotten', TRUE),
                        updated_at = NOW()
                    WHERE id = $1 AND superseded_by IS NULL
                    """,
                    entry_id,
                )
        # asyncpg returns "DELETE n" / "UPDATE n"
        # asyncpg reports "UPDATE <n>" / "DELETE <n>"; 0 means nothing matched.
        return str(result).split()[-1] != "0"

    async def set_pinned(self, entry_id: UUID, pinned: bool) -> bool:
        """Pin/unpin an active entry.

        Pinned entries render verbatim in the always-injected context. Returns True if a row was
        updated.
        """
        async with self._acquire() as conn:
            result = await conn.execute(
                """
                UPDATE memory_entries SET pinned = $2, updated_at = NOW()
                WHERE id = $1 AND superseded_by IS NULL
                """,
                entry_id, pinned,
            )
        # asyncpg reports "UPDATE <n>" / "DELETE <n>"; 0 means nothing matched.
        return str(result).split()[-1] != "0"

    async def mark_verified(self, entry_id: UUID) -> bool:
        """Record that a fact was just confirmed to still hold.

        Resets its staleness clock. Returns True if a row was updated.
        """
        async with self._acquire() as conn:
            result = await conn.execute(
                "UPDATE memory_entries SET verified_at = NOW() WHERE id = $1 AND superseded_by IS "
                "NULL",
                entry_id,
            )
        # asyncpg reports "UPDATE <n>" / "DELETE <n>"; 0 means nothing matched.
        return str(result).split()[-1] != "0"

    async def list_pinned(self, persona_id: str) -> list[MemoryEntry]:
        """All active pinned entries for a persona, newest first."""
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT * FROM memory_entries
                WHERE persona_id = $1 AND pinned AND superseded_by IS NULL
                ORDER BY created_at DESC
                """,
                persona_id,
            )
        return [_entry(r) for r in rows]

    # ---- recall ----

    async def list_active(
        self,
        persona_id: str,
        scope: str | None = None,
        domain_key: str | None = None,
        limit: int = 200,
    ) -> list[MemoryEntry]:
        sql = [
            "SELECT * FROM memory_entries",
            "WHERE persona_id = $1 AND superseded_by IS NULL",
        ]
        params: list[Any] = [persona_id]
        if scope is not None:
            sql.append(f"AND scope = ${len(params) + 1}")
            params.append(scope)
        if domain_key is not None:
            sql.append(f"AND domain_key = ${len(params) + 1}")
            params.append(domain_key)
        sql.append("ORDER BY created_at DESC")
        sql.append(f"LIMIT ${len(params) + 1}")
        params.append(limit)
        async with self._acquire() as conn:
            rows = await conn.fetch("\n".join(sql), *params)
        return [_entry(r) for r in rows]

    async def recall(
        self,
        persona_id: str,
        query: str,
        scope: str | None = None,
        domain_key: str | None = None,
        limit: int = 8,
    ) -> list[MemoryEntry]:
        scored = await self.recall_scored(
            persona_id, query, scope=scope, domain_key=domain_key, limit=limit,
        )
        return [e for e, _ in scored]

    async def recall_scored(
        self,
        persona_id: str,
        query: str,
        scope: str | None = None,
        domain_key: str | None = None,
        limit: int = 8,
    ) -> list[Scored]:
        """Hybrid search over active entries, fused with Reciprocal Rank Fusion.

        Three arms rank the candidate pool independently:
          fts    — FTS relevance over title+content (keyword).
          trg    — trigram similarity (short identifiers, slugs, typos).
          vec    — local-embedding cosine (semantic / paraphrase).

        Each arm contributes 1/(RRF_K + rank) for the rows it found; the sum
        is normalized by the maximum an arm-complete rank-1 hit could score,
        so `match_score` is 0..1 and comparable ACROSS queries. A row ranked
        first by all three arms scores ~1.0; one found only by the vector arm
        tops out near 0.33. That is the intended signal — agreement between
        independent retrieval strategies is evidence, and callers that
        auto-inject memories threshold on it.

        The vector arm is active only when the query embeds successfully AND
        the stored vector came from the current embedding model (rows from an
        older model still match via FTS/trigram until re-embedded).

        FTS matching is OR-of-tokens, not plainto_tsquery's AND-of-tokens — a
        natural-language query ("where does the user work") must not require
        every filler word to appear in the fact.

        Returns (entry, score) pairs, best first.
        """
        qpg = await _embed_pg(self._embed, query, is_query=True)
        # OR-semantics token query; tokens are \w+ so to_tsquery is safe.
        tokens = re.findall(r"\w+", query, flags=re.UNICODE)[:12]
        or_query = " | ".join(tokens) if tokens else ""

        # One statement, always the same shape. Everything that varies between
        # calls is a bound parameter -- including which arms can fire, which is
        # expressed as "this parameter is NULL" rather than as absent SQL.
        #
        # The arms were assembled from fragments before. That made the text a
        # different string per call, which costs a plan every time and puts the
        # statement the database runs somewhere no reader can see it whole.
        fts_query = or_query or None
        vector = qpg or None

        # Which arms can fire. Fixed up front (not "which arms returned rows")
        # so the normalizer is deterministic and scores stay comparable between
        # queries run under the same configuration.
        active_weight = (
            (RRF_WEIGHT_FTS if fts_query else 0.0)
            + RRF_WEIGHT_TRG
            + (RRF_WEIGHT_VEC if vector else 0.0)
        )
        max_rrf = (active_weight or 1.0) * (1.0 / (RRF_K + 1))

        # Pull a deeper slice than the caller asked for when a reranker will
        # re-sort it — fusion only has to get the right answer into the pool,
        # the cross-encoder decides the final order.
        fetch_n = max(limit, self._rerank.candidates) if self._rerank.available() else limit

        params: list[Any] = [
            persona_id,             # $1
            query,                  # $2  trigram probe
            fts_query,              # $3  OR-of-tokens tsquery, NULL to skip the arm
            scope,                  # $4  NULL = no compartment filter
            domain_key,             # $5
            vector,                 # $6  NULL to skip the vector arm
            self._embed.model_name,  # $7
            VEC_MIN_SIMILARITY,     # $8
            RRF_CANDIDATES,         # $9
            RRF_K,                  # $10
            RRF_WEIGHT_FTS,         # $11
            RRF_WEIGHT_TRG,         # $12
            RRF_WEIGHT_VEC,         # $13
            max_rrf,                # $14
            RECENCY_BOOST_MAX,      # $15
            RECENCY_HALFLIFE_DAYS,  # $16
            fetch_n,                # $17
        ]
        sql = _RECALL_SQL
        async with self._acquire() as conn:
            rows = await conn.fetch(sql, *params)

        scored = [(_entry(r), float(r["match_score"] or 0)) for r in rows]
        return await self._rerank_scored(query, scored, limit)

    async def _rerank_scored(
        self,
        query: str,
        scored: list[tuple[MemoryEntry, float]],
        limit: int,
    ) -> list[Scored]:
        """Re-score fused candidates with the cross-encoder and truncate.

        The returned score becomes the RERANKER's calibrated 0..1 relevance,
        replacing the RRF score rather than blending with it — blending would
        reintroduce the compressed range that makes RRF scores unthresholdable
        (see storage.reranking). If reranking is off or fails, RRF scores pass
        through untouched and ordering is unchanged.
        """
        if not scored:
            return scored
        texts = [
            (f"{e.title}\n{e.content}" if e.title else e.content) for e, _ in scored
        ]
        rescored = await asyncio.to_thread(self._rerank.rerank, query, texts)
        if rescored is None:
            return scored[:limit]
        pairs = [(entry, score) for (entry, _), score in zip(scored, rescored, strict=False)]
        pairs.sort(key=lambda p: p[1], reverse=True)
        return pairs[:limit]

    async def backfill_embeddings(self, force: bool = False) -> int:
        """Compute and store embeddings for entries missing them.

        With force=True, for every entry not embedded by the CURRENT model —
        run this once after an embedding-model change: `cli.py memory reembed`.
        Returns the count re-embedded.
        """
        if force:
            sql = _UNEMBEDDED_FOR_MODEL
            args: tuple[Any, ...] = (self._embed.model_name,)
        else:
            sql = _UNEMBEDDED
            args = ()
        async with self._acquire() as conn:
            rows = await conn.fetch(sql, *args)
        done = 0
        for r in rows:
            text = f"{r['title']}\n{r['content']}" if r["title"] else r["content"]
            pg = await _embed_pg(self._embed, text)
            if not pg:
                continue
            async with self._acquire() as conn:
                await conn.execute(
                    """
                    UPDATE memory_entries
                    SET embedding = $1::vector, embedding_model = $2
                    WHERE id = $3
                    """,
                    pg, self._embed.model_name, r["id"],
                )
            done += 1
        return done

    async def counts_by_scope(self, persona_id: str) -> dict[str, int]:
        """Active entry counts per scope — surfaced by /status."""
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT scope, COUNT(*) AS n FROM memory_entries
                WHERE persona_id = $1 AND superseded_by IS NULL
                GROUP BY scope
                """,
                persona_id,
            )
        return {r["scope"]: int(r["n"]) for r in rows}

    async def count_active(
        self,
        persona_id: str,
        scope: str,
        domain_key: str = "",
    ) -> int:
        async with self._acquire() as conn:
            count = await conn.fetchval(
                """
                SELECT COUNT(*)
                FROM memory_entries
                WHERE persona_id = $1 AND scope = $2 AND domain_key = $3
                  AND superseded_by IS NULL
                """,
                persona_id, scope, domain_key,
            )
        return int(count or 0)

    # ---- core summary ----

    async def get_core(self, persona_id: str) -> list[MemoryCoreEntry]:
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT * FROM memory_core
                WHERE persona_id = $1
                ORDER BY scope, domain_key
                """,
                persona_id,
            )
        return [
            MemoryCoreEntry(
                persona_id=r["persona_id"],
                scope=r["scope"],
                domain_key=r["domain_key"],
                summary=r["summary"],
                last_source_count=r["last_source_count"],
                last_compacted_at=r["last_compacted_at"],
            )
            for r in rows
        ]

    async def set_core(
        self,
        persona_id: str,
        scope: str,
        domain_key: str,
        summary: str,
        source_count: int,
    ) -> None:
        async with self._acquire() as conn:
            await conn.execute(
                """
                INSERT INTO memory_core
                    (persona_id, scope, domain_key, summary,
                     last_source_count, last_compacted_at)
                VALUES ($1, $2, $3, $4, $5, NOW())
                ON CONFLICT (persona_id, scope, domain_key)
                DO UPDATE SET
                    summary = EXCLUDED.summary,
                    last_source_count = EXCLUDED.last_source_count,
                    last_compacted_at = NOW()
                """,
                persona_id, scope, domain_key, summary, source_count,
            )

    async def fetch(self, sql: str, *args: Any) -> list[asyncpg.Record]:
        """Execute a SELECT and return all rows. For ad-hoc inspection only."""
        async with self._acquire() as conn:
            rows: list[asyncpg.Record] = await conn.fetch(sql, *args)
        return rows

    async def purge_persona(self, persona_id: str) -> int:
        """Delete every entry belonging to one persona. Returns the count.

        Destructive and deliberately so: the recall eval seeds a scratch
        persona and has to leave the database as it found it. Nothing in the
        running bot calls this — retirement goes through forget/supersede,
        which keep the row.
        """
        async with self._acquire() as conn:
            rows = await conn.fetch(
                "DELETE FROM memory_entries WHERE persona_id = $1 RETURNING id", persona_id
            )
        return len(rows)

    async def warmup(self) -> None:
        """Load the retrieval models before anyone is waiting on a query.

        Both are lazy by design — importing fastembed pulls in onnxruntime, and
        a persona with memory disabled should never pay that. But "lazy" used
        to mean "on the first user turn", which put a ~600MB model load in the
        middle of somebody's first message.
        """
        await asyncio.to_thread(self._embed.warmup)
        await asyncio.to_thread(self._rerank.warmup)

    # ---- internals ----

    def _acquire(self) -> asyncpg.pool.PoolAcquireContext:
        if self._pool is None:
            raise RuntimeError("MemoryDatabase.connect() not called yet")
        return self._pool.acquire()


def _jsonb_encoder(obj: Any) -> str:
    return json.dumps(obj)


def _jsonb_decoder(raw: str) -> Any:
    return json.loads(raw)


def _dsn_host(dsn: str) -> str:
    """Just the hostname, for a log line that shouldn't carry a whole DSN.

    Use `redact_dsn` when the operator needs to recognise WHICH database.
    """
    try:
        return urlparse(dsn).hostname or "?"
    except Exception:
        return "?"
