"""Async Postgres client for the memory layer.

One MemoryDatabase per persona container (one connection pool per process).
On startup, init_schema() applies the idempotent schema. Recall is hybrid:
Postgres FTS (`tsvector`) + trigram + local semantic embeddings (pgvector
cosine). Embeddings are generated by a local model (see storage.embeddings),
so recall stays provider-independent.
"""
from __future__ import annotations

import asyncio
import json
import logging
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Optional
from urllib.parse import urlparse
from uuid import UUID

import asyncpg

from .embeddings import MODEL_NAME as _EMBED_MODEL, embed as _embed, to_pgvector as _to_pgvector

log = logging.getLogger(__name__)


async def _embed_pg(text: str) -> Optional[str]:
    """Compute a pgvector literal for `text` off the event loop; None on failure."""
    try:
        vec = await asyncio.to_thread(_embed, text)
        return _to_pgvector(vec)
    except Exception:
        log.debug("embedding failed; continuing without a vector", exc_info=True)
        return None

_SCHEMA_PATH = Path(__file__).parent / "schema.sql"


@dataclass
class MemoryEntry:
    id: UUID
    persona_id: str
    scope: str
    domain_key: str
    title: str
    content: str
    metadata: dict[str, Any]
    superseded_by: Optional[UUID]
    created_at: datetime
    updated_at: datetime
    pinned: bool = False

    @classmethod
    def from_row(cls, row: asyncpg.Record) -> "MemoryEntry":
        return cls(
            id=row["id"],
            persona_id=row["persona_id"],
            scope=row["scope"],
            domain_key=row["domain_key"],
            title=row["title"],
            content=row["content"],
            metadata=dict(row["metadata"] or {}),
            superseded_by=row["superseded_by"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            pinned=bool(row["pinned"]) if "pinned" in row else False,
        )


@dataclass
class MemoryCoreEntry:
    persona_id: str
    scope: str
    domain_key: str
    summary: str
    last_source_count: int
    last_compacted_at: datetime


class MemoryDatabase:
    """Async Postgres-backed memory store.

    Construct one per persona container. Call `init_schema` at startup once
    the pool is created (it's idempotent — safe to call repeatedly).
    """

    def __init__(self, dsn: str) -> None:
        self._dsn = dsn
        self._pool: Optional[asyncpg.Pool] = None

    async def connect(self) -> None:
        if self._pool is not None:
            return
        # JSONB codec must be registered on every connection the pool hands
        # out; set_type_codec only sticks for the conn it's called on.
        async def _init_conn(conn: asyncpg.Connection) -> None:
            await conn.set_type_codec(
                "jsonb",
                encoder=_jsonb_encoder,
                decoder=_jsonb_decoder,
                schema="pg_catalog",
            )
        self._pool = await asyncpg.create_pool(
            self._dsn, min_size=1, max_size=4, init=_init_conn,
        )
        log.info("memory database connected (dsn host=%s)", _redact_dsn(self._dsn))

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    async def init_schema(self) -> None:
        sql = _SCHEMA_PATH.read_text(encoding="utf-8")
        async with self._acquire() as conn:
            await conn.execute(sql)

    # ---- entry CRUD ----

    async def save_entry(
        self,
        persona_id: str,
        scope: str,
        content: str,
        domain_key: str = "",
        title: str = "",
        metadata: Optional[dict[str, Any]] = None,
    ) -> MemoryEntry:
        emb = await _embed_pg(f"{title}\n{content}" if title else content)
        async with self._acquire() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO memory_entries
                    (persona_id, scope, domain_key, title, content, metadata,
                     embedding, embedding_model)
                VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::vector, $8)
                RETURNING *
                """,
                persona_id, scope, domain_key, title, content, metadata or {},
                emb, _EMBED_MODEL if emb else "",
            )
        return MemoryEntry.from_row(row)

    async def find_similar(
        self,
        persona_id: str,
        scope: str,
        domain_key: str,
        content: str,
        threshold: float = 0.90,
    ) -> Optional[tuple[MemoryEntry, float]]:
        """Nearest active entry in the same compartment by embedding cosine
        similarity, if it clears `threshold`. Used to dedup near-identical
        saves (the model re-learning the same fact) before they accumulate.
        Returns (entry, similarity) or None. Trigram fallback when the
        embedding isn't available."""
        qpg = await _embed_pg(content)
        async with self._acquire() as conn:
            if qpg:
                row = await conn.fetchrow(
                    """
                    SELECT *, (1 - (embedding <=> $4::vector)) AS sim
                    FROM memory_entries
                    WHERE persona_id = $1 AND scope = $2 AND domain_key = $3
                      AND superseded_by IS NULL
                      AND embedding IS NOT NULL AND embedding_model = $5
                    ORDER BY embedding <=> $4::vector
                    LIMIT 1
                    """,
                    persona_id, scope, domain_key, qpg, _EMBED_MODEL,
                )
            else:
                row = await conn.fetchrow(
                    """
                    SELECT *, similarity(content, $4) AS sim
                    FROM memory_entries
                    WHERE persona_id = $1 AND scope = $2 AND domain_key = $3
                      AND superseded_by IS NULL
                    ORDER BY similarity(content, $4) DESC
                    LIMIT 1
                    """,
                    persona_id, scope, domain_key, content,
                )
        if row is None or float(row["sim"] or 0) < threshold:
            return None
        return MemoryEntry.from_row(row), float(row["sim"])

    async def get_entry(self, entry_id: UUID) -> Optional[MemoryEntry]:
        async with self._acquire() as conn:
            row = await conn.fetchrow(
                "SELECT * FROM memory_entries WHERE id = $1", entry_id
            )
        return MemoryEntry.from_row(row) if row else None

    async def supersede_entry(
        self,
        old_id: UUID,
        new_content: str,
    ) -> Optional[MemoryEntry]:
        """Insert a new active entry that replaces `old_id`. Marks the old
        row's `superseded_by` to the new id. Returns the new entry, or None
        if the old id wasn't found / already superseded."""
        async with self._acquire() as conn:
            async with conn.transaction():
                old = await conn.fetchrow(
                    """
                    SELECT * FROM memory_entries
                    WHERE id = $1 AND superseded_by IS NULL
                    """,
                    old_id,
                )
                if old is None:
                    return None
                emb = await _embed_pg(
                    f"{old['title']}\n{new_content}" if old["title"] else new_content)
                new = await conn.fetchrow(
                    """
                    INSERT INTO memory_entries
                        (persona_id, scope, domain_key, title, content, metadata,
                         embedding, embedding_model, pinned)
                    VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::vector, $8, $9)
                    RETURNING *
                    """,
                    old["persona_id"], old["scope"], old["domain_key"],
                    old["title"], new_content, dict(old["metadata"] or {}),
                    emb, _EMBED_MODEL if emb else "", old["pinned"],
                )
                await conn.execute(
                    "UPDATE memory_entries SET superseded_by = $1, updated_at = NOW() WHERE id = $2",
                    new["id"], old["id"],
                )
                # Carry the old entry's graph edges onto its replacement so a
                # correction doesn't orphan the fact's relationships. The new
                # row was just inserted and has no edges of its own, so no PK
                # collision is possible here.
                await conn.execute(
                    "UPDATE memory_links SET from_id = $1 WHERE from_id = $2",
                    new["id"], old["id"],
                )
                await conn.execute(
                    "UPDATE memory_links SET to_id = $1 WHERE to_id = $2",
                    new["id"], old["id"],
                )
        return MemoryEntry.from_row(new)

    # ---- links (typed edges between entries) ----

    async def add_link(
        self,
        from_id: UUID,
        to_id: UUID,
        relation: str = "relates_to",
    ) -> bool:
        """Create a directional edge from_id --relation--> to_id. Idempotent:
        returns True if a new edge was created, False if it already existed."""
        async with self._acquire() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO memory_links (from_id, to_id, relation)
                VALUES ($1, $2, $3)
                ON CONFLICT (from_id, to_id, relation) DO NOTHING
                RETURNING from_id
                """,
                from_id, to_id, relation,
            )
        return row is not None

    async def remove_link(
        self,
        from_id: UUID,
        to_id: UUID,
        relation: Optional[str] = None,
    ) -> bool:
        """Delete the edge(s) between two entries. With `relation`, only that
        edge; without it, every edge from_id->to_id. Returns True if anything
        was deleted."""
        async with self._acquire() as conn:
            if relation is not None:
                result = await conn.execute(
                    "DELETE FROM memory_links WHERE from_id = $1 AND to_id = $2 AND relation = $3",
                    from_id, to_id, relation,
                )
            else:
                result = await conn.execute(
                    "DELETE FROM memory_links WHERE from_id = $1 AND to_id = $2",
                    from_id, to_id,
                )
        return result.split()[-1] != "0"

    async def neighbors(
        self,
        entry_id: UUID,
    ) -> list[tuple[MemoryEntry, str, str]]:
        """Directly-linked ACTIVE entries. Returns (neighbor, relation,
        direction) where direction is 'out' (entry_id --rel--> neighbor) or
        'in' (neighbor --rel--> entry_id). Superseded/forgotten neighbors are
        excluded so recall never surfaces stale links."""
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT m.*, l.relation AS _rel, 'out' AS _dir
                FROM memory_links l JOIN memory_entries m ON m.id = l.to_id
                WHERE l.from_id = $1 AND m.superseded_by IS NULL
                UNION ALL
                SELECT m.*, l.relation AS _rel, 'in' AS _dir
                FROM memory_links l JOIN memory_entries m ON m.id = l.from_id
                WHERE l.to_id = $1 AND m.superseded_by IS NULL
                """,
                entry_id,
            )
        return [(MemoryEntry.from_row(r), r["_rel"], r["_dir"]) for r in rows]

    async def forget_entry(self, entry_id: UUID, hard: bool = False) -> bool:
        async with self._acquire() as conn:
            if hard:
                result = await conn.execute(
                    "DELETE FROM memory_entries WHERE id = $1", entry_id
                )
            else:
                # Soft-delete: mark in metadata and supersede with itself so
                # it drops out of "active" queries. We use a sentinel UUID
                # set to the entry itself to mark it tombstoned without
                # losing provenance.
                result = await conn.execute(
                    """
                    UPDATE memory_entries
                    SET superseded_by = id,
                        metadata = metadata || jsonb_build_object('forgotten', TRUE),
                        updated_at = NOW()
                    WHERE id = $1 AND superseded_by IS NULL
                    """,
                    entry_id,
                )
        # asyncpg returns "DELETE n" / "UPDATE n"
        return result.split()[-1] != "0"

    async def set_pinned(self, entry_id: UUID, pinned: bool) -> bool:
        """Pin/unpin an active entry. Pinned entries render verbatim in the
        always-injected context. Returns True if a row was updated."""
        async with self._acquire() as conn:
            result = await conn.execute(
                """
                UPDATE memory_entries SET pinned = $2, updated_at = NOW()
                WHERE id = $1 AND superseded_by IS NULL
                """,
                entry_id, pinned,
            )
        return result.split()[-1] != "0"

    async def list_pinned(self, persona_id: str) -> list[MemoryEntry]:
        """All active pinned entries for a persona, newest first."""
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT * FROM memory_entries
                WHERE persona_id = $1 AND pinned AND superseded_by IS NULL
                ORDER BY created_at DESC
                """,
                persona_id,
            )
        return [MemoryEntry.from_row(r) for r in rows]

    # ---- recall ----

    async def list_active(
        self,
        persona_id: str,
        scope: Optional[str] = None,
        domain_key: Optional[str] = None,
        limit: int = 200,
    ) -> list[MemoryEntry]:
        sql = [
            "SELECT * FROM memory_entries",
            "WHERE persona_id = $1 AND superseded_by IS NULL",
        ]
        params: list[Any] = [persona_id]
        if scope is not None:
            sql.append(f"AND scope = ${len(params) + 1}")
            params.append(scope)
        if domain_key is not None:
            sql.append(f"AND domain_key = ${len(params) + 1}")
            params.append(domain_key)
        sql.append("ORDER BY created_at DESC")
        sql.append(f"LIMIT ${len(params) + 1}")
        params.append(limit)
        async with self._acquire() as conn:
            rows = await conn.fetch("\n".join(sql), *params)
        return [MemoryEntry.from_row(r) for r in rows]

    async def recall(
        self,
        persona_id: str,
        query: str,
        scope: Optional[str] = None,
        domain_key: Optional[str] = None,
        limit: int = 8,
    ) -> list[MemoryEntry]:
        scored = await self.recall_scored(
            persona_id, query, scope=scope, domain_key=domain_key, limit=limit,
        )
        return [e for e, _ in scored]

    async def recall_scored(
        self,
        persona_id: str,
        query: str,
        scope: Optional[str] = None,
        domain_key: Optional[str] = None,
        limit: int = 8,
    ) -> list[tuple[MemoryEntry, float]]:
        """Hybrid search over active entries — three signals, max-combined:
          ts_rank    — FTS relevance over title+content (keyword).
          similarity — trigram similarity (short queries / typos).
          vec_score  — local-embedding cosine similarity (semantic / paraphrase).
        Vector signal is included only when the query embeds successfully AND
        the stored vector came from the current embedding model (stale rows
        from an older model still match via FTS/trigram).

        Ranking gets a small recency boost (up to +0.08, ~60-day half-life)
        so a fresh fact outranks a stale near-equal one.

        FTS matching is OR-of-tokens, not plainto_tsquery's AND-of-tokens —
        a natural-language query ("where does the user work") must not
        require every filler word to appear in the fact.

        Returns (entry, score) pairs — callers that inject memories
        automatically use the score to filter noise.
        """
        qpg = await _embed_pg(query)
        # OR-semantics token query; tokens are \w+ so to_tsquery is safe.
        tokens = re.findall(r"\w+", query, flags=re.UNICODE)[:12]
        or_query = " | ".join(tokens) if tokens else ""
        params: list[Any] = [persona_id, query, or_query]
        vec_idx: Optional[int] = None
        if qpg:
            params.append(qpg)
            vec_idx = len(params)  # $4
        vec_guard = (
            f"(m.embedding IS NOT NULL AND m.embedding_model = '{_EMBED_MODEL}')"
        )
        vec_expr = (
            f"(CASE WHEN {vec_guard} THEN (1 - (m.embedding <=> ${vec_idx}::vector)) ELSE 0.0 END)"
            if vec_idx else "0.0"
        )
        recency_boost = (
            "0.08 * EXP(-EXTRACT(EPOCH FROM (NOW() - m.created_at)) / (60.0 * 86400.0))"
        )
        base_score = (
            "GREATEST("
            "ts_rank(content_tsv, to_tsquery('simple', $3)), "
            f"similarity(content, $2), {vec_expr})"
        )

        sql = [
            "SELECT m.*,",
            f"  ({base_score} + {recency_boost}) AS match_score",
            "FROM memory_entries m",
            "WHERE persona_id = $1 AND superseded_by IS NULL",
            "  AND (",
            "    ($3 <> '' AND content_tsv @@ to_tsquery('simple', $3))",
            "    OR content % $2",
        ]
        if vec_idx:
            sql.append(f"    OR {vec_expr} > 0.45")
        sql.append("  )")
        if scope is not None:
            sql.append(f"AND scope = ${len(params) + 1}")
            params.append(scope)
        if domain_key is not None:
            sql.append(f"AND domain_key = ${len(params) + 1}")
            params.append(domain_key)
        sql.append("ORDER BY match_score DESC")
        sql.append(f"LIMIT ${len(params) + 1}")
        params.append(limit)
        async with self._acquire() as conn:
            rows = await conn.fetch("\n".join(sql), *params)
        return [(MemoryEntry.from_row(r), float(r["match_score"] or 0)) for r in rows]

    async def backfill_embeddings(self, force: bool = False) -> int:
        """Compute + store embeddings for entries missing them (or, with
        force=True, every entry not embedded by the CURRENT model — run this
        once after an embedding-model change: `cli.py memory reembed`).
        Returns the count re-embedded."""
        if force:
            where = "embedding IS NULL OR embedding_model IS DISTINCT FROM $1"
            args: tuple = (_EMBED_MODEL,)
        else:
            where = "embedding IS NULL"
            args = ()
        async with self._acquire() as conn:
            rows = await conn.fetch(
                f"SELECT id, title, content FROM memory_entries WHERE {where}", *args
            )
        done = 0
        for r in rows:
            text = f"{r['title']}\n{r['content']}" if r["title"] else r["content"]
            pg = await _embed_pg(text)
            if not pg:
                continue
            async with self._acquire() as conn:
                await conn.execute(
                    """
                    UPDATE memory_entries
                    SET embedding = $1::vector, embedding_model = $2
                    WHERE id = $3
                    """,
                    pg, _EMBED_MODEL, r["id"],
                )
            done += 1
        return done

    async def counts_by_scope(self, persona_id: str) -> dict[str, int]:
        """Active entry counts per scope — surfaced by /status."""
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT scope, COUNT(*) AS n FROM memory_entries
                WHERE persona_id = $1 AND superseded_by IS NULL
                GROUP BY scope
                """,
                persona_id,
            )
        return {r["scope"]: int(r["n"]) for r in rows}

    async def count_active(
        self,
        persona_id: str,
        scope: str,
        domain_key: str = "",
    ) -> int:
        async with self._acquire() as conn:
            return await conn.fetchval(
                """
                SELECT COUNT(*)
                FROM memory_entries
                WHERE persona_id = $1 AND scope = $2 AND domain_key = $3
                  AND superseded_by IS NULL
                """,
                persona_id, scope, domain_key,
            )

    # ---- core summary ----

    async def get_core(self, persona_id: str) -> list[MemoryCoreEntry]:
        async with self._acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT * FROM memory_core
                WHERE persona_id = $1
                ORDER BY scope, domain_key
                """,
                persona_id,
            )
        return [
            MemoryCoreEntry(
                persona_id=r["persona_id"],
                scope=r["scope"],
                domain_key=r["domain_key"],
                summary=r["summary"],
                last_source_count=r["last_source_count"],
                last_compacted_at=r["last_compacted_at"],
            )
            for r in rows
        ]

    async def set_core(
        self,
        persona_id: str,
        scope: str,
        domain_key: str,
        summary: str,
        source_count: int,
    ) -> None:
        async with self._acquire() as conn:
            await conn.execute(
                """
                INSERT INTO memory_core (persona_id, scope, domain_key, summary, last_source_count, last_compacted_at)
                VALUES ($1, $2, $3, $4, $5, NOW())
                ON CONFLICT (persona_id, scope, domain_key)
                DO UPDATE SET
                    summary = EXCLUDED.summary,
                    last_source_count = EXCLUDED.last_source_count,
                    last_compacted_at = NOW()
                """,
                persona_id, scope, domain_key, summary, source_count,
            )

    async def fetch(self, sql: str, *args):
        """Execute a SELECT and return all rows. For ad-hoc inspection only."""
        async with self._acquire() as conn:
            return await conn.fetch(sql, *args)

    # ---- internals ----

    def _acquire(self):
        if self._pool is None:
            raise RuntimeError("MemoryDatabase.connect() not called yet")
        return self._pool.acquire()


def _jsonb_encoder(obj: Any) -> str:
    return json.dumps(obj)


def _jsonb_decoder(raw: str) -> Any:
    return json.loads(raw)


def _redact_dsn(dsn: str) -> str:
    """Return a host-only fragment for safe logging."""
    try:
        return urlparse(dsn).hostname or "?"
    except Exception:
        return "?"
